import { FAQ } from "./components/FAQ";
import { OFFER, checkoutUrl } from "./offer-config";

const heroBenefits = ["Ideias prontas para aplicar", "Materiais simples", "Para diferentes idades e espaços"];
const pains = [
  { icon: "⏱", title: "As crianças perdem o interesse rápido", text: "Você prepara uma brincadeira, mas em poucos minutos já precisa inventar outra." },
  { icon: "▣", title: "As telas acabam dominando", text: "Quando faltam alternativas, celular, videogame e televisão viram a solução mais fácil." },
  { icon: "⌁", title: "Falta tempo para planejar", text: "Pesquisar regras, materiais e atividades para várias idades consome horas." },
  { icon: "◇", title: "Nem toda brincadeira funciona", text: "Espaço, idade, quantidade de crianças e segurança mudam completamente a dinâmica." },
];
const audience = ["Vai organizar uma festa infantil em casa ou no salão.", "Quer reduzir o uso de telas durante a comemoração.", "Precisa entreter crianças de idades diferentes.", "Não quer gastar muito com brinquedos e equipamentos.", "Trabalha como recreador, professor, cuidador ou animador.", "Quer ter um plano pronto sem depender de improvisação."];
const transformations = [
  { icon: "↗", title: "Participação de verdade", text: "Crianças brincando e criando em vez de apenas assistindo." }, { icon: "✦", title: "Novas conexões", text: "Mais interação entre convidados que ainda não se conhecem." },
  { icon: "↻", title: "Ritmo equilibrado", text: "Movimento, criatividade, cooperação e calma na medida certa." }, { icon: "✓", title: "Adultos mais tranquilos", text: "Organização simples para quem conduz a diversão." },
  { icon: "∞", title: "Todos no jogo", text: "Brincadeiras inclusivas, sem longas eliminações." }, { icon: "♡", title: "Memórias reais", text: "Experiências vividas que continuam depois da festa." },
];
const blocks = [["01", "Aquecimento e integração", "Para quebrar o gelo e formar o grupo"], ["02", "Movimento e energia", "Para correr, pular e gastar energia"], ["03", "Criatividade e imaginação", "Para inventar, desenhar e encenar"], ["04", "Cooperação e equipe", "Para resolver desafios juntos"], ["05", "Calma e encerramento", "Para desacelerar sem perder a graça"]];
const details = ["Faixa etária", "Participantes", "Duração", "Espaço", "Materiais", "Passo a passo", "Variação", "Segurança"];
const games = [["Caça às Cores", "4–7 anos", "10 min", "Exploração", "#fce7a6"], ["Espelho Encantado", "4–8 anos", "8 min", "Integração", "#d9f3ec"], ["Circuito dos Animais", "5–10 anos", "15 min", "Movimento", "#f8d2c7"], ["Travessia do Rio", "6–12 anos", "15 min", "Cooperação", "#dceaf5"], ["Monstro Coletivo", "5–12 anos", "20 min", "Criatividade", "#e5ddf0"], ["Bola no Lençol", "6–12 anos", "12 min", "Equipe", "#d9f3ec"], ["Quebra-Cabeça Gigante", "7–12 anos", "20 min", "Desafio", "#fce7a6"], ["Memória da Bandeja", "5–12 anos", "10 min", "Calma", "#f8d2c7"]];
const extras = [["2h", "Roteiro sugerido", "Uma sequência equilibrada para uma festa de duas horas."], ["✓", "Planejamento rápido", "Um jeito simples de montar a sua própria sequência."], ["☑", "Checklist do adulto", "O que conferir antes, durante e depois da festa."], ["♢", "Segurança e adaptação", "Orientações para adequar cada proposta ao seu grupo."], ["⌕", "Índice prático", "Encontre atividades rapidamente quando precisar."]];
const offerItems = ["40 atividades completas", "Crianças de 4 a 12 anos", "Materiais simples e de baixo custo", "Passo a passo e variações", "Orientações de segurança", "Roteiro de festa", "Checklist e planejamento", "Acesso ao material digital"];
const faqs = [
  ["Como receberei o material?", `O acesso ao ${OFFER.format.toLowerCase()} é liberado após a confirmação do pagamento, conforme o fluxo da plataforma escolhida para o checkout.`], ["O produto é físico ou digital?", "É um produto exclusivamente digital. Você não receberá nenhum item físico ou encomenda pelos Correios."],
  ["Para quais idades as dinâmicas foram criadas?", "As propostas atendem crianças de 4 a 12 anos. Cada dinâmica traz sua faixa etária indicada para facilitar a escolha."], ["Preciso comprar materiais especiais?", "Não. O guia prioriza objetos simples, acessíveis e que muitas famílias já têm em casa."],
  ["As brincadeiras funcionam em espaços pequenos?", "Sim. O material indica o espaço recomendado e inclui opções que podem ser adaptadas para casa, salão, escola ou quintal."], ["Posso usar o guia trabalhando como recreador ou professor?", "Sim. Recreadores, professores, cuidadores e animadores podem usar o guia para conduzir atividades. O arquivo não pode ser revendido, distribuído ou compartilhado."],
  ["O material ajuda a montar a sequência da festa?", "Sim. Além das dinâmicas, o guia inclui um roteiro sugerido de duas horas e uma estrutura rápida de planejamento."], ["Como funciona a garantia?", `Você tem ${OFFER.guaranteeDays} dias para avaliar o conteúdo e solicitar o reembolso dentro desse prazo, conforme as condições da plataforma de pagamento.`],
];

function SectionTitle({ eyebrow, title, text, light = false }: { eyebrow: string; title: string; text?: string; light?: boolean }) { return <header className={`section-title${light ? " section-title-light" : ""}`}><span>{eyebrow}</span><h2>{title}</h2>{text && <p>{text}</p>}</header>; }
function CTA({ children, light = false }: { children: React.ReactNode; light?: boolean }) { return <a className={`button ${light ? "button-light" : "button-primary"}`} href={checkoutUrl}>{children}<span aria-hidden="true">→</span></a>; }
function EbookMockup({ compact = false }: { compact?: boolean }) { return <div className={`mockup-stage${compact ? " mockup-compact" : ""}`} aria-label="Capa ilustrativa do e-book"><div className="confetti confetti-one" /><div className="confetti confetti-two" /><div className="book-shadow" /><div className="book"><div className="book-spine" aria-hidden="true" /><div className="book-cover"><span className="cover-kicker">GUIA PRÁTICO</span><strong className="cover-number">40</strong><span className="cover-title">Dinâmicas para<br />Festas Infantis</span><span className="cover-ribbon">sem eletrônicos</span><div className="cover-play" aria-hidden="true"><span>★</span><span>●</span><span>✦</span></div><small>Brincadeiras para criar memórias de verdade</small></div><div className="book-pages" aria-hidden="true" /></div>{!compact && <div className="age-card"><strong>4–12</strong><span>anos</span></div>}</div>; }

export default function Home() { return <main>
  <div className="topbar">Produto digital <span>•</span> Acesso após a confirmação do pagamento</div>
  <section className="hero" id="inicio"><div className="hero-copy"><div className="eyebrow"><span aria-hidden="true">★</span> Brincadeiras para crianças de 4 a 12 anos</div><h1>Transforme a festa em uma <em>aventura</em> sem celular, videogame ou televisão</h1><p className="hero-lead">Tenha 40 dinâmicas simples, divertidas e de baixo custo para manter as crianças brincando, criando e interagindo de verdade.</p><ul className="hero-benefits">{heroBenefits.map((item) => <li key={item}><span aria-hidden="true">✓</span>{item}</li>)}</ul><CTA>Quero as 40 dinâmicas</CTA><p className="microcopy">Material digital <span>•</span> Consulte os detalhes da oferta</p></div><EbookMockup /></section>
  <section className="section pain-section"><div className="container"><SectionTitle eyebrow="A gente entende" title="Organizar a diversão da festa não deveria virar mais uma preocupação" text="Entre bolo, convidados e decoração, inventar como entreter todo mundo não precisa ficar nas suas costas." /><div className="card-grid four-grid">{pains.map((pain) => <article className="pain-card" key={pain.title}><span className="card-icon" aria-hidden="true">{pain.icon}</span><h3>{pain.title}</h3><p>{pain.text}</p></article>)}</div></div></section>
  <section className="section audience-section"><div className="container split-layout"><div><SectionTitle eyebrow="Para quem é" title="Este guia foi feito para você que…" /><p className="side-copy">Quer ver a criançada se divertindo de verdade — e também deseja aproveitar a festa sem passar o tempo todo improvisando.</p></div><ul className="check-panel">{audience.map((item) => <li key={item}><span aria-hidden="true">✓</span>{item}</li>)}</ul></div></section>
  <section className="section transformation-section"><div className="container"><SectionTitle eyebrow="A experiência muda" title="Menos tela. Mais movimento, imaginação e conexão." text="Uma festa memorável não precisa de telas, brinquedos caros ou horas de improviso." /><div className="card-grid three-grid">{transformations.map((item) => <article className="benefit-card" key={item.title}><span className="round-icon" aria-hidden="true">{item.icon}</span><div><h3>{item.title}</h3><p>{item.text}</p></div></article>)}</div></div></section>
  <section className="section included-section" id="conteudo"><div className="container"><SectionTitle eyebrow="Por dentro do guia" title="40 dinâmicas prontas para salvar a sua festa" text="Atividades organizadas pelo ritmo da comemoração, para você saber o que propor em cada momento." /><div className="blocks-layout"><ol className="blocks-list">{blocks.map(([number, title, text]) => <li key={number}><strong>{number}</strong><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol><div className="inside-preview"><div className="preview-paper preview-back"><span>03</span></div><div className="preview-paper preview-front"><span className="preview-label">DINÂMICA 12</span><h3>Circuito dos Animais</h3><div className="preview-meta"><span>5–10 anos</span><span>15 min</span><span>Movimento</span></div><div className="preview-lines"><i/><i/><i/><i/></div><div className="preview-tip">Dica de adaptação</div></div></div></div><div className="detail-strip"><p>Cada dinâmica informa:</p><div>{details.map((detail) => <span key={detail}><b aria-hidden="true">✓</b>{detail}</span>)}</div></div></div></section>
  <section className="section games-section"><div className="container"><SectionTitle eyebrow="Um gostinho do material" title="Dá uma olhada em algumas brincadeiras que você vai encontrar" text="Informações rápidas ajudam você a escolher sem revelar todo o passo a passo." /><div className="games-grid">{games.map(([name, age, time, type, color], index) => <article className="game-card" key={name} style={{ "--game-color": color } as React.CSSProperties}><div className="game-number">{String(index + 1).padStart(2, "0")}</div><span className="game-type">{type}</span><h3>{name}</h3><div className="game-meta"><span>◷ {time}</span><span>☺ {age}</span></div></article>)}</div></div></section>
  <section className="section how-section"><div className="container"><SectionTitle eyebrow="Simples de usar" title="Sua próxima festa organizada em três passos" /><ol className="steps"><li><span>1</span><h3>Escolha</h3><p>Consulte o índice e encontre a atividade ideal para a idade, o espaço e o momento da festa.</p></li><li><span>2</span><h3>Prepare</h3><p>Separe materiais simples que você provavelmente já tem em casa.</p></li><li><span>3</span><h3>Conduza</h3><p>Siga o passo a passo, aplique as adaptações e aproveite a brincadeira junto com as crianças.</p></li></ol></div></section>
  <section className="section extras-section"><div className="container"><SectionTitle eyebrow="Tudo no mesmo guia" title="Além das 40 dinâmicas, você também recebe" text="Recursos incluídos para tirar a organização do papel e transformar ideias em uma festa gostosa de viver." /><div className="extras-grid">{extras.map(([icon, title, text]) => <article key={title}><span aria-hidden="true">{icon}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
  <section className="section value-section"><div className="container value-layout"><div><SectionTitle eyebrow="O que você leva" title="Você não está comprando apenas uma lista de brincadeiras" light /><p>Você está comprando tranquilidade para organizar a festa, segurança para conduzir as atividades e tempo para aproveitar o momento junto com as crianças.</p><CTA light>Quero planejar sem improviso</CTA></div><div className="value-card"><div><span>Sem o guia</span><p>Pesquisas espalhadas</p><p>Dúvida sobre o que funciona</p><p>Improviso durante a festa</p></div><div><span>Com o guia</span><p>40 opções organizadas</p><p>Informações para escolher melhor</p><p>Uma sequência pronta para adaptar</p></div></div></div></section>
  <section className="section offer-section" id="oferta"><div className="container offer-wrap"><div className="offer-visual"><EbookMockup compact /><div className="digital-stamp"><b>100%</b><span>digital</span></div></div><article className="offer-card"><span className="offer-label">OFERTA PRINCIPAL</span><h2>{OFFER.productName}</h2><p className="offer-intro">Seu guia prático para uma festa mais leve, participativa e longe das telas.</p><ul>{offerItems.map((item) => <li key={item}><span aria-hidden="true">✓</span>{item}</li>)}</ul><div className="price"><small>Por apenas</small><strong>{OFFER.currentPrice}</strong><span>pagamento único</span></div><CTA>Quero organizar uma festa sem telas</CTA><p className="secure-note">♢ Compra protegida <span>•</span> {OFFER.delivery}</p></article></div></section>
  <section className="section guarantee-section"><div className="container guarantee-card"><div className="shield" aria-hidden="true">✓</div><div><span className="mini-eyebrow">GARANTIA DE {OFFER.guaranteeDays} DIAS</span><h2>Você pode conhecer o material com tranquilidade</h2><p>Você terá {OFFER.guaranteeDays} dias para avaliar o conteúdo. Se entender que o guia não atende ao que procura, poderá solicitar o reembolso dentro desse prazo, conforme as condições da plataforma de pagamento.</p></div></div></section>
  <section className="section faq-section" id="duvidas"><div className="container faq-layout"><div><SectionTitle eyebrow="Perguntas frequentes" title="Antes de começar a brincadeira…" text="Reunimos as respostas para você decidir com clareza e tranquilidade." /></div><FAQ items={faqs} /></div></section>
  <section className="section final-section"><div className="container final-cta"><span className="party-mark" aria-hidden="true">✦ ◦ ★ ◦ ✦</span><h2>Pronto para trocar as telas por uma festa cheia de brincadeiras?</h2><p>Escolha as dinâmicas, separe materiais simples e crie uma experiência que as crianças realmente vão lembrar.</p><CTA>Quero receber as 40 dinâmicas</CTA></div></section>
  <footer><div className="container footer-inner"><div><strong>Brinca de Verdade</strong><p>{OFFER.productName}</p></div><div className="legal-links"><a href="/termos">Termos de Uso</a><a href="/privacidade">Política de Privacidade</a></div><p>Produto digital. Nenhum item físico será enviado.</p></div><div className="footer-bottom">© {new Date().getFullYear()} Brinca de Verdade. Todos os direitos reservados.</div></footer>
</main>; }
